// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/transcodev1/transcoder.proto

package transcodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscodeService_ListProfiles_FullMethodName       = "/muxcore.transcoder.v1.TranscodeService/ListProfiles"
	TranscodeService_CreateProfile_FullMethodName      = "/muxcore.transcoder.v1.TranscodeService/CreateProfile"
	TranscodeService_UpdateProfile_FullMethodName      = "/muxcore.transcoder.v1.TranscodeService/UpdateProfile"
	TranscodeService_DeleteProfile_FullMethodName      = "/muxcore.transcoder.v1.TranscodeService/DeleteProfile"
	TranscodeService_Enqueue_FullMethodName            = "/muxcore.transcoder.v1.TranscodeService/Enqueue"
	TranscodeService_CancelJob_FullMethodName          = "/muxcore.transcoder.v1.TranscodeService/CancelJob"
	TranscodeService_ListJobs_FullMethodName           = "/muxcore.transcoder.v1.TranscodeService/ListJobs"
	TranscodeService_GetJob_FullMethodName             = "/muxcore.transcoder.v1.TranscodeService/GetJob"
	TranscodeService_DetectHardware_FullMethodName     = "/muxcore.transcoder.v1.TranscodeService/DetectHardware"
	TranscodeService_ListSetups_FullMethodName         = "/muxcore.transcoder.v1.TranscodeService/ListSetups"
	TranscodeService_GetSetup_FullMethodName           = "/muxcore.transcoder.v1.TranscodeService/GetSetup"
	TranscodeService_UpsertSetup_FullMethodName        = "/muxcore.transcoder.v1.TranscodeService/UpsertSetup"
	TranscodeService_DeleteSetup_FullMethodName        = "/muxcore.transcoder.v1.TranscodeService/DeleteSetup"
	TranscodeService_ProcessFile_FullMethodName        = "/muxcore.transcoder.v1.TranscodeService/ProcessFile"
	TranscodeService_ScanSetups_FullMethodName         = "/muxcore.transcoder.v1.TranscodeService/ScanSetups"
	TranscodeService_ListPipelineRuns_FullMethodName   = "/muxcore.transcoder.v1.TranscodeService/ListPipelineRuns"
	TranscodeService_GetPipelineRun_FullMethodName     = "/muxcore.transcoder.v1.TranscodeService/GetPipelineRun"
	TranscodeService_ApprovePipelineRun_FullMethodName = "/muxcore.transcoder.v1.TranscodeService/ApprovePipelineRun"
	TranscodeService_RejectPipelineRun_FullMethodName  = "/muxcore.transcoder.v1.TranscodeService/RejectPipelineRun"
	TranscodeService_ListStepTemplates_FullMethodName  = "/muxcore.transcoder.v1.TranscodeService/ListStepTemplates"
	TranscodeService_ApplyStepTemplate_FullMethodName  = "/muxcore.transcoder.v1.TranscodeService/ApplyStepTemplate"
)

// TranscodeServiceClient is the client API for TranscodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscodeServiceClient interface {
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	DetectHardware(ctx context.Context, in *DetectHardwareRequest, opts ...grpc.CallOption) (*DetectHardwareResponse, error)
	// Tdarr-style configurable pipelines (setups / plugin stacks)
	ListSetups(ctx context.Context, in *ListSetupsRequest, opts ...grpc.CallOption) (*ListSetupsResponse, error)
	GetSetup(ctx context.Context, in *GetSetupRequest, opts ...grpc.CallOption) (*GetSetupResponse, error)
	UpsertSetup(ctx context.Context, in *UpsertSetupRequest, opts ...grpc.CallOption) (*UpsertSetupResponse, error)
	DeleteSetup(ctx context.Context, in *DeleteSetupRequest, opts ...grpc.CallOption) (*DeleteSetupResponse, error)
	ProcessFile(ctx context.Context, in *ProcessFileRequest, opts ...grpc.CallOption) (*ProcessFileResponse, error)
	ScanSetups(ctx context.Context, in *ScanSetupsRequest, opts ...grpc.CallOption) (*ScanSetupsResponse, error)
	ListPipelineRuns(ctx context.Context, in *ListPipelineRunsRequest, opts ...grpc.CallOption) (*ListPipelineRunsResponse, error)
	GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*GetPipelineRunResponse, error)
	ApprovePipelineRun(ctx context.Context, in *ApprovePipelineRunRequest, opts ...grpc.CallOption) (*ApprovePipelineRunResponse, error)
	RejectPipelineRun(ctx context.Context, in *RejectPipelineRunRequest, opts ...grpc.CallOption) (*RejectPipelineRunResponse, error)
	ListStepTemplates(ctx context.Context, in *ListStepTemplatesRequest, opts ...grpc.CallOption) (*ListStepTemplatesResponse, error)
	ApplyStepTemplate(ctx context.Context, in *ApplyStepTemplateRequest, opts ...grpc.CallOption) (*ApplyStepTemplateResponse, error)
}

type transcodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscodeServiceClient(cc grpc.ClientConnInterface) TranscodeServiceClient {
	return &transcodeServiceClient{cc}
}

func (c *transcodeServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, TranscodeService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, TranscodeService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, TranscodeService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, TranscodeService_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, TranscodeService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, TranscodeService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) DetectHardware(ctx context.Context, in *DetectHardwareRequest, opts ...grpc.CallOption) (*DetectHardwareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectHardwareResponse)
	err := c.cc.Invoke(ctx, TranscodeService_DetectHardware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ListSetups(ctx context.Context, in *ListSetupsRequest, opts ...grpc.CallOption) (*ListSetupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSetupsResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ListSetups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetSetup(ctx context.Context, in *GetSetupRequest, opts ...grpc.CallOption) (*GetSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSetupResponse)
	err := c.cc.Invoke(ctx, TranscodeService_GetSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) UpsertSetup(ctx context.Context, in *UpsertSetupRequest, opts ...grpc.CallOption) (*UpsertSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSetupResponse)
	err := c.cc.Invoke(ctx, TranscodeService_UpsertSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) DeleteSetup(ctx context.Context, in *DeleteSetupRequest, opts ...grpc.CallOption) (*DeleteSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSetupResponse)
	err := c.cc.Invoke(ctx, TranscodeService_DeleteSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ProcessFile(ctx context.Context, in *ProcessFileRequest, opts ...grpc.CallOption) (*ProcessFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessFileResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ProcessFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ScanSetups(ctx context.Context, in *ScanSetupsRequest, opts ...grpc.CallOption) (*ScanSetupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanSetupsResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ScanSetups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ListPipelineRuns(ctx context.Context, in *ListPipelineRunsRequest, opts ...grpc.CallOption) (*ListPipelineRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPipelineRunsResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ListPipelineRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*GetPipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineRunResponse)
	err := c.cc.Invoke(ctx, TranscodeService_GetPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ApprovePipelineRun(ctx context.Context, in *ApprovePipelineRunRequest, opts ...grpc.CallOption) (*ApprovePipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePipelineRunResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ApprovePipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) RejectPipelineRun(ctx context.Context, in *RejectPipelineRunRequest, opts ...grpc.CallOption) (*RejectPipelineRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectPipelineRunResponse)
	err := c.cc.Invoke(ctx, TranscodeService_RejectPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ListStepTemplates(ctx context.Context, in *ListStepTemplatesRequest, opts ...grpc.CallOption) (*ListStepTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStepTemplatesResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ListStepTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ApplyStepTemplate(ctx context.Context, in *ApplyStepTemplateRequest, opts ...grpc.CallOption) (*ApplyStepTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyStepTemplateResponse)
	err := c.cc.Invoke(ctx, TranscodeService_ApplyStepTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscodeServiceServer is the server API for TranscodeService service.
// All implementations must embed UnimplementedTranscodeServiceServer
// for forward compatibility.
type TranscodeServiceServer interface {
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	DetectHardware(context.Context, *DetectHardwareRequest) (*DetectHardwareResponse, error)
	// Tdarr-style configurable pipelines (setups / plugin stacks)
	ListSetups(context.Context, *ListSetupsRequest) (*ListSetupsResponse, error)
	GetSetup(context.Context, *GetSetupRequest) (*GetSetupResponse, error)
	UpsertSetup(context.Context, *UpsertSetupRequest) (*UpsertSetupResponse, error)
	DeleteSetup(context.Context, *DeleteSetupRequest) (*DeleteSetupResponse, error)
	ProcessFile(context.Context, *ProcessFileRequest) (*ProcessFileResponse, error)
	ScanSetups(context.Context, *ScanSetupsRequest) (*ScanSetupsResponse, error)
	ListPipelineRuns(context.Context, *ListPipelineRunsRequest) (*ListPipelineRunsResponse, error)
	GetPipelineRun(context.Context, *GetPipelineRunRequest) (*GetPipelineRunResponse, error)
	ApprovePipelineRun(context.Context, *ApprovePipelineRunRequest) (*ApprovePipelineRunResponse, error)
	RejectPipelineRun(context.Context, *RejectPipelineRunRequest) (*RejectPipelineRunResponse, error)
	ListStepTemplates(context.Context, *ListStepTemplatesRequest) (*ListStepTemplatesResponse, error)
	ApplyStepTemplate(context.Context, *ApplyStepTemplateRequest) (*ApplyStepTemplateResponse, error)
	mustEmbedUnimplementedTranscodeServiceServer()
}

// UnimplementedTranscodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscodeServiceServer struct{}

func (UnimplementedTranscodeServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedTranscodeServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedTranscodeServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedTranscodeServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedTranscodeServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedTranscodeServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedTranscodeServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedTranscodeServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedTranscodeServiceServer) DetectHardware(context.Context, *DetectHardwareRequest) (*DetectHardwareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectHardware not implemented")
}
func (UnimplementedTranscodeServiceServer) ListSetups(context.Context, *ListSetupsRequest) (*ListSetupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSetups not implemented")
}
func (UnimplementedTranscodeServiceServer) GetSetup(context.Context, *GetSetupRequest) (*GetSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetup not implemented")
}
func (UnimplementedTranscodeServiceServer) UpsertSetup(context.Context, *UpsertSetupRequest) (*UpsertSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertSetup not implemented")
}
func (UnimplementedTranscodeServiceServer) DeleteSetup(context.Context, *DeleteSetupRequest) (*DeleteSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSetup not implemented")
}
func (UnimplementedTranscodeServiceServer) ProcessFile(context.Context, *ProcessFileRequest) (*ProcessFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessFile not implemented")
}
func (UnimplementedTranscodeServiceServer) ScanSetups(context.Context, *ScanSetupsRequest) (*ScanSetupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanSetups not implemented")
}
func (UnimplementedTranscodeServiceServer) ListPipelineRuns(context.Context, *ListPipelineRunsRequest) (*ListPipelineRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPipelineRuns not implemented")
}
func (UnimplementedTranscodeServiceServer) GetPipelineRun(context.Context, *GetPipelineRunRequest) (*GetPipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipelineRun not implemented")
}
func (UnimplementedTranscodeServiceServer) ApprovePipelineRun(context.Context, *ApprovePipelineRunRequest) (*ApprovePipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePipelineRun not implemented")
}
func (UnimplementedTranscodeServiceServer) RejectPipelineRun(context.Context, *RejectPipelineRunRequest) (*RejectPipelineRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectPipelineRun not implemented")
}
func (UnimplementedTranscodeServiceServer) ListStepTemplates(context.Context, *ListStepTemplatesRequest) (*ListStepTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStepTemplates not implemented")
}
func (UnimplementedTranscodeServiceServer) ApplyStepTemplate(context.Context, *ApplyStepTemplateRequest) (*ApplyStepTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyStepTemplate not implemented")
}
func (UnimplementedTranscodeServiceServer) mustEmbedUnimplementedTranscodeServiceServer() {}
func (UnimplementedTranscodeServiceServer) testEmbeddedByValue()                          {}

// UnsafeTranscodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscodeServiceServer will
// result in compilation errors.
type UnsafeTranscodeServiceServer interface {
	mustEmbedUnimplementedTranscodeServiceServer()
}

func RegisterTranscodeServiceServer(s grpc.ServiceRegistrar, srv TranscodeServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscodeService_ServiceDesc, srv)
}

func _TranscodeService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_DetectHardware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectHardwareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).DetectHardware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_DetectHardware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).DetectHardware(ctx, req.(*DetectHardwareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ListSetups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSetupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListSetups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListSetups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListSetups(ctx, req.(*ListSetupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetSetup(ctx, req.(*GetSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_UpsertSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).UpsertSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_UpsertSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).UpsertSetup(ctx, req.(*UpsertSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_DeleteSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).DeleteSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_DeleteSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).DeleteSetup(ctx, req.(*DeleteSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ProcessFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ProcessFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ProcessFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ProcessFile(ctx, req.(*ProcessFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ScanSetups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanSetupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ScanSetups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ScanSetups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ScanSetups(ctx, req.(*ScanSetupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ListPipelineRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelineRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListPipelineRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListPipelineRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListPipelineRuns(ctx, req.(*ListPipelineRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetPipelineRun(ctx, req.(*GetPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ApprovePipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ApprovePipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ApprovePipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ApprovePipelineRun(ctx, req.(*ApprovePipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_RejectPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).RejectPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_RejectPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).RejectPipelineRun(ctx, req.(*RejectPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ListStepTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListStepTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListStepTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListStepTemplates(ctx, req.(*ListStepTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ApplyStepTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyStepTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ApplyStepTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ApplyStepTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ApplyStepTemplate(ctx, req.(*ApplyStepTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscodeService_ServiceDesc is the grpc.ServiceDesc for TranscodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.transcoder.v1.TranscodeService",
	HandlerType: (*TranscodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProfiles",
			Handler:    _TranscodeService_ListProfiles_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _TranscodeService_CreateProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _TranscodeService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _TranscodeService_DeleteProfile_Handler,
		},
		{
			MethodName: "Enqueue",
			Handler:    _TranscodeService_Enqueue_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _TranscodeService_CancelJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _TranscodeService_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _TranscodeService_GetJob_Handler,
		},
		{
			MethodName: "DetectHardware",
			Handler:    _TranscodeService_DetectHardware_Handler,
		},
		{
			MethodName: "ListSetups",
			Handler:    _TranscodeService_ListSetups_Handler,
		},
		{
			MethodName: "GetSetup",
			Handler:    _TranscodeService_GetSetup_Handler,
		},
		{
			MethodName: "UpsertSetup",
			Handler:    _TranscodeService_UpsertSetup_Handler,
		},
		{
			MethodName: "DeleteSetup",
			Handler:    _TranscodeService_DeleteSetup_Handler,
		},
		{
			MethodName: "ProcessFile",
			Handler:    _TranscodeService_ProcessFile_Handler,
		},
		{
			MethodName: "ScanSetups",
			Handler:    _TranscodeService_ScanSetups_Handler,
		},
		{
			MethodName: "ListPipelineRuns",
			Handler:    _TranscodeService_ListPipelineRuns_Handler,
		},
		{
			MethodName: "GetPipelineRun",
			Handler:    _TranscodeService_GetPipelineRun_Handler,
		},
		{
			MethodName: "ApprovePipelineRun",
			Handler:    _TranscodeService_ApprovePipelineRun_Handler,
		},
		{
			MethodName: "RejectPipelineRun",
			Handler:    _TranscodeService_RejectPipelineRun_Handler,
		},
		{
			MethodName: "ListStepTemplates",
			Handler:    _TranscodeService_ListStepTemplates_Handler,
		},
		{
			MethodName: "ApplyStepTemplate",
			Handler:    _TranscodeService_ApplyStepTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transcodev1/transcoder.proto",
}
